// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCrOjFti2Nm5WS_H2fP0s0EdmN8Rl4pXw',
    appId: '1:174543887846:web:37bea6d41862ad09f64a27',
    messagingSenderId: '174543887846',
    projectId: 'pawspartnersfinal',
    authDomain: 'pawspartnersfinal.firebaseapp.com',
    storageBucket: 'pawspartnersfinal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-EN0dexQu3WwHYE60HJYSkEeZGSWsp5o',
    appId: '1:174543887846:android:cf8b3ba90c6c262af64a27',
    messagingSenderId: '174543887846',
    projectId: 'pawspartnersfinal',
    storageBucket: 'pawspartnersfinal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV-E6jYXia5ftmUhV-WNQwugZ725dUW6I',
    appId: '1:174543887846:ios:64447b279a3e4615f64a27',
    messagingSenderId: '174543887846',
    projectId: 'pawspartnersfinal',
    storageBucket: 'pawspartnersfinal.appspot.com',
    iosBundleId: 'com.example.netwealthVjti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV-E6jYXia5ftmUhV-WNQwugZ725dUW6I',
    appId: '1:174543887846:ios:64447b279a3e4615f64a27',
    messagingSenderId: '174543887846',
    projectId: 'pawspartnersfinal',
    storageBucket: 'pawspartnersfinal.appspot.com',
    iosBundleId: 'com.example.netwealthVjti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcrVG349lTtI0LtClUjMDpJsdxftjlLLM',
    appId: '1:174543887846:web:f6663f3109a0cb2af64a27',
    messagingSenderId: '174543887846',
    projectId: 'pawspartnersfinal',
    authDomain: 'pawspartnersfinal.firebaseapp.com',
    storageBucket: 'pawspartnersfinal.appspot.com',
  );

}